LOCATIONS = [
    # city, region, area, location_type, city_lat, city_lon
    ("Karachi", "Sindh", "Clifton Block 5", "Urban", 24.8138, 67.0300),
    ("Karachi", "Sindh", "DHA Phase 6", "Suburban", 24.7960, 67.0650),
    ("Karachi", "Sindh", "Dolmen Mall Clifton", "Mall", 24.8020, 67.0290),
    ("Karachi", "Sindh", "Saddar", "Downtown", 24.8560, 67.0290),
    ("Karachi", "Sindh", "Gulshan-e-Iqbal", "Suburban", 24.9200, 67.0930),
    ("Karachi", "Sindh", "Super Highway Toll Plaza", "Highway", 25.0680, 67.2950),
    ("Lahore", "Punjab", "Gulberg III", "Urban", 31.5100, 74.3440),
    ("Lahore", "Punjab", "MM Alam Road", "Downtown", 31.5160, 74.3510),
    ("Lahore", "Punjab", "Emporium Mall Johar Town", "Mall", 31.4670, 74.2660),
    ("Lahore", "Punjab", "DHA Phase 5", "Suburban", 31.4630, 74.4080),
    ("Lahore", "Punjab", "Johar Town", "Suburban", 31.4690, 74.2720),
    ("Islamabad", "Islamabad Capital Territory", "Blue Area", "Downtown", 33.7100, 73.0600),
    ("Islamabad", "Islamabad Capital Territory", "F-7 Markaz", "Urban", 33.7210, 73.0560),
    ("Islamabad", "Islamabad Capital Territory", "Centaurus Mall", "Mall", 33.7080, 73.0500),
    ("Rawalpindi", "Punjab", "Saddar", "Downtown", 33.5970, 73.0520),
    ("Rawalpindi", "Punjab", "Bahria Town Phase 7", "Suburban", 33.5300, 73.1000),
    ("Faisalabad", "Punjab", "D Ground", "Urban", 31.4180, 73.0790),
    ("Faisalabad", "Punjab", "Lyallpur Galleria", "Mall", 31.4020, 73.1030),
    ("Multan", "Punjab", "Bosan Road", "Urban", 30.2150, 71.4750),
    ("Peshawar", "Khyber Pakhtunkhwa", "University Road", "Urban", 34.0000, 71.4850),
    ("Peshawar", "Khyber Pakhtunkhwa", "Hayatabad Phase 3", "Suburban", 33.9900, 71.4400),
    ("Hyderabad", "Sindh", "Auto Bhan Road", "Urban", 25.3790, 68.3680),
    ("Quetta", "Balochistan", "Jinnah Road", "Downtown", 30.1920, 67.0070),
    ("Bhera", "Punjab", "M-2 Motorway Service Area", "Highway", 32.4400, 72.8900),
    ("Nowshera", "Khyber Pakhtunkhwa", "M-1 Motorway Service Area", "Highway", 34.0100, 71.9500),
]

TAX_RATE_BY_REGION = {
    "Sindh": 0.15,
    "Punjab": 0.16,
    "Islamabad Capital Territory": 0.15,
    "Khyber Pakhtunkhwa": 0.15,
    "Balochistan": 0.15,
}

LOCATION_TYPES = ["Urban", "Suburban", "Mall", "Highway", "Downtown"]

# category_name, description, demand weight, unit, portion size in that unit
CATEGORIES = [
    ("Appetizers", "Starters and small plates served before the main meal", 0.9, "pcs", 1.0),
    ("Soups", "Hot soups served by the bowl", 0.6, "liters", 0.30),
    ("Salads", "Fresh salads and chaats", 0.6, "pcs", 1.0),
    ("BBQ & Grills", "Charcoal grilled kababs, tikkas and platters", 1.2, "kg", 0.30),
    ("Karahi & Handi", "Traditional curries cooked in karahi or handi", 1.1, "kg", 0.50),
    ("Rice & Biryani", "Biryani, pulao and rice dishes", 1.4, "kg", 0.40),
    ("Burgers & Wraps", "Burgers, wraps and sandwiches", 1.3, "pcs", 1.0),
    ("Pizza", "Medium and family size pizzas", 1.0, "pcs", 1.0),
    ("Pasta", "Italian and fusion pasta dishes", 0.7, "pcs", 1.0),
    ("Seafood", "Fish and prawn dishes", 0.5, "kg", 0.35),
    ("Desserts", "Traditional and continental desserts", 0.8, "pcs", 1.0),
    ("Hot Beverages", "Tea and coffee", 1.0, "liters", 0.25),
    ("Cold Beverages & Shakes", "Soft drinks, juices, shakes and mocktails", 1.5, "liters", 0.35),
    ("Sides & Breads", "Fries, naan, roti and other sides", 1.6, "pcs", 1.0),
]

# category_name, item_name, price in PKR at the start of 2025
MENU = [
    ("Appetizers", "Chicken Samosa", 250), ("Appetizers", "Vegetable Samosa", 200),
    ("Appetizers", "Aloo Pakora", 350), ("Appetizers", "Chicken Pakora", 550),
    ("Appetizers", "Dahi Bhallay", 400), ("Appetizers", "Chicken Wings (6 pcs)", 750),
    ("Appetizers", "Chicken Wings Bucket", 1650), ("Appetizers", "Loaded Nachos", 950),
    ("Appetizers", "Veg Spring Rolls", 450), ("Appetizers", "Dynamite Prawns", 1350),
    ("Appetizers", "Chicken Tempura", 890), ("Appetizers", "Crispy Fish Bites", 850),
    ("Appetizers", "Papri Chaat", 380),
    ("Soups", "Chicken Corn Soup", 450), ("Soups", "Hot & Sour Soup", 480),
    ("Soups", "Cream of Mushroom Soup", 520), ("Soups", "Thai Tom Yum Soup", 650),
    ("Soups", "Mutton Yakhni", 550), ("Soups", "Lentil Soup", 350),
    ("Soups", "Seafood Soup", 780), ("Soups", "Tomato Basil Soup", 420),
    ("Soups", "Chicken Noodle Soup", 460),
    ("Salads", "Fresh Garden Salad", 450), ("Salads", "Caesar Salad", 750),
    ("Salads", "Greek Salad", 780), ("Salads", "Russian Salad", 520),
    ("Salads", "Fruit Chaat", 400), ("Salads", "Chickpea Chaat", 380),
    ("Salads", "Grilled Chicken Salad", 890), ("Salads", "Kachumber Salad", 250),
    ("Salads", "Quinoa Power Bowl", 1100),
    ("BBQ & Grills", "Chicken Tikka", 750), ("BBQ & Grills", "Seekh Kabab", 850),
    ("BBQ & Grills", "Malai Boti", 950), ("BBQ & Grills", "Reshmi Kabab", 900),
    ("BBQ & Grills", "Chicken Boti", 800), ("BBQ & Grills", "Mutton Chops", 2200),
    ("BBQ & Grills", "Beef Bihari Boti", 1100), ("BBQ & Grills", "Gola Kabab", 950),
    ("BBQ & Grills", "Chapli Kabab", 700), ("BBQ & Grills", "Tandoori Chicken (Half)", 1200),
    ("BBQ & Grills", "BBQ Platter for 4", 5500), ("BBQ & Grills", "Mutton Raan", 4800),
    ("BBQ & Grills", "Grilled Fish Tikka", 1350),
    ("Karahi & Handi", "Chicken Karahi (Half)", 1450), ("Karahi & Handi", "Mutton Karahi (Half)", 2600),
    ("Karahi & Handi", "Chicken White Karahi", 1550), ("Karahi & Handi", "Chicken Handi", 1400),
    ("Karahi & Handi", "Mutton Handi", 2450), ("Karahi & Handi", "Peshawari Karahi", 1650),
    ("Karahi & Handi", "Daal Makhni", 650), ("Karahi & Handi", "Palak Paneer", 750),
    ("Karahi & Handi", "Chicken Jalfrezi", 1250), ("Karahi & Handi", "Nihari", 1150),
    ("Karahi & Handi", "Haleem", 650), ("Karahi & Handi", "Butter Chicken", 1350),
    ("Rice & Biryani", "Chicken Biryani", 650), ("Rice & Biryani", "Mutton Biryani", 950),
    ("Rice & Biryani", "Sindhi Biryani", 700), ("Rice & Biryani", "Beef Pulao", 750),
    ("Rice & Biryani", "Mutton Pulao", 950), ("Rice & Biryani", "Chicken Fried Rice", 750),
    ("Rice & Biryani", "Egg Fried Rice", 550), ("Rice & Biryani", "Vegetable Biryani", 500),
    ("Rice & Biryani", "Prawn Biryani", 1250), ("Rice & Biryani", "Kabuli Pulao", 900),
    ("Rice & Biryani", "Steamed Rice", 300),
    ("Burgers & Wraps", "Zinger Burger", 650), ("Burgers & Wraps", "Classic Beef Burger", 850),
    ("Burgers & Wraps", "Double Patty Burger", 1350), ("Burgers & Wraps", "Chicken Tikka Wrap", 650),
    ("Burgers & Wraps", "Grilled Chicken Burger", 750), ("Burgers & Wraps", "Fish Burger", 800),
    ("Burgers & Wraps", "Mushroom Swiss Burger", 1150), ("Burgers & Wraps", "Crispy Chicken Wrap", 600),
    ("Burgers & Wraps", "Chapli Kabab Burger", 700), ("Burgers & Wraps", "Club Sandwich", 750),
    ("Burgers & Wraps", "Smash Burger", 1250), ("Burgers & Wraps", "Korean Fried Chicken Burger", 1100),
    ("Burgers & Wraps", "Nashville Hot Wrap", 950),
    ("Pizza", "Chicken Tikka Pizza (Medium)", 1450), ("Pizza", "Fajita Pizza (Medium)", 1500),
    ("Pizza", "Pepperoni Pizza (Medium)", 1650), ("Pizza", "Margherita Pizza (Medium)", 1200),
    ("Pizza", "BBQ Chicken Pizza (Medium)", 1550), ("Pizza", "Vegetable Supreme Pizza (Medium)", 1300),
    ("Pizza", "Jumbo Family Pizza", 3200), ("Pizza", "Malai Boti Pizza (Medium)", 1600),
    ("Pizza", "Seafood Pizza (Medium)", 1950), ("Pizza", "Four Cheese Pizza (Medium)", 1750),
    ("Pizza", "Kebab Crust Pizza (Medium)", 1850),
    ("Pasta", "Alfredo Pasta", 1150), ("Pasta", "Arrabbiata Pasta", 1050),
    ("Pasta", "Beef Lasagna", 1450), ("Pasta", "Chicken Mac and Cheese", 1100),
    ("Pasta", "Truffle Mushroom Pasta", 1650), ("Pasta", "Pink Sauce Pasta", 1200),
    ("Pasta", "Spaghetti Bolognese", 1150), ("Pasta", "Pesto Pasta", 1250),
    ("Pasta", "Crunchy Chicken Pasta", 1200), ("Pasta", "Baked Chicken Penne", 1150),
    ("Seafood", "Fried Fish Lahori", 1300), ("Seafood", "Grilled Prawns Platter", 2900),
    ("Seafood", "Finger Fish", 1100), ("Seafood", "Prawn Karahi", 2400),
    ("Seafood", "Grilled Salmon Steak", 3800), ("Seafood", "Fish and Chips", 1350),
    ("Seafood", "Lemon Butter Fish", 1650), ("Seafood", "Masala Fish", 1450),
    ("Seafood", "Calamari Rings", 1250),
    ("Desserts", "Gulab Jamun", 250), ("Desserts", "Kheer", 300),
    ("Desserts", "Gajar Halwa", 450), ("Desserts", "Kulfi", 250),
    ("Desserts", "Falooda", 550), ("Desserts", "Molten Lava Cake", 750),
    ("Desserts", "Tiramisu", 850), ("Desserts", "Brownie Sundae", 700),
    ("Desserts", "Shahi Tukray", 450), ("Desserts", "Kunafa Cheesecake", 950),
    ("Desserts", "Rasmalai", 350), ("Desserts", "Chocolate Fudge Cake", 650),
    ("Desserts", "Zarda", 300),
    ("Hot Beverages", "Doodh Patti Chai", 180), ("Hot Beverages", "Kashmiri Chai", 280),
    ("Hot Beverages", "Green Tea", 150), ("Hot Beverages", "Cappuccino", 480),
    ("Hot Beverages", "Cafe Latte", 480), ("Hot Beverages", "Hot Chocolate", 520),
    ("Hot Beverages", "Karak Chai", 220), ("Hot Beverages", "Espresso", 350),
    ("Hot Beverages", "Americano", 380), ("Hot Beverages", "Mint Tea", 170),
    ("Cold Beverages & Shakes", "Soft Drink (Regular)", 150),
    ("Cold Beverages & Shakes", "Mineral Water (500ml)", 100),
    ("Cold Beverages & Shakes", "Mango Shake", 450), ("Cold Beverages & Shakes", "Sweet Lassi", 300),
    ("Cold Beverages & Shakes", "Fresh Lime Soda", 250), ("Cold Beverages & Shakes", "Mint Margarita", 380),
    ("Cold Beverages & Shakes", "Blue Lagoon", 420), ("Cold Beverages & Shakes", "Cold Coffee", 480),
    ("Cold Beverages & Shakes", "Oreo Shake", 580), ("Cold Beverages & Shakes", "Strawberry Shake", 520),
    ("Cold Beverages & Shakes", "Lotus Biscoff Shake", 750),
    ("Cold Beverages & Shakes", "Peach Iced Tea", 350),
    ("Cold Beverages & Shakes", "Chocolate Shake", 550),
    ("Cold Beverages & Shakes", "Fresh Orange Juice", 420),
    ("Sides & Breads", "Plain Fries", 300), ("Sides & Breads", "Masala Fries", 350),
    ("Sides & Breads", "Garlic Naan", 120), ("Sides & Breads", "Plain Naan", 60),
    ("Sides & Breads", "Roghni Naan", 90), ("Sides & Breads", "Tandoori Roti", 40),
    ("Sides & Breads", "Garlic Bread", 350), ("Sides & Breads", "Coleslaw", 200),
    ("Sides & Breads", "Raita", 120), ("Sides & Breads", "Loaded Fries", 750),
    ("Sides & Breads", "Mashed Potatoes", 350), ("Sides & Breads", "Onion Rings", 450),
    ("Sides & Breads", "Paratha", 100),
]

HIGH_VOLUME_LOW_MARGIN = [
    "Chicken Biryani", "Zinger Burger", "Chicken Tikka Pizza (Medium)", "Doodh Patti Chai",
    "Soft Drink (Regular)", "Mineral Water (500ml)", "Plain Fries", "Plain Naan",
]
HIGH_MARGIN_LOW_VOLUME = [
    "Loaded Nachos", "Truffle Mushroom Pasta", "Molten Lava Cake", "Tiramisu",
    "Cappuccino", "Cafe Latte", "Mint Margarita", "Blue Lagoon",
]
HIGH_WASTAGE_POPULAR = [
    "Fresh Garden Salad", "Seekh Kabab", "Chicken Karahi (Half)", "Mutton Karahi (Half)",
    "Chicken Handi", "Fried Fish Lahori",
]
POORLY_RATED = ["Veg Spring Rolls", "Mutton Pulao", "Fish Burger", "Beef Lasagna", "Cold Coffee"]
PROMOTION_DEPENDENT = [
    "Chicken Wings Bucket", "BBQ Platter for 4", "Double Patty Burger",
    "Jumbo Family Pizza", "Brownie Sundae",
]

SEASONAL_ITEMS = {
    "Summer": ["Fruit Chaat", "Kulfi", "Falooda", "Mango Shake", "Sweet Lassi", "Fresh Lime Soda"],
    "Winter": [
        "Chicken Corn Soup", "Hot & Sour Soup", "Cream of Mushroom Soup", "Mutton Yakhni",
        "Chicken Noodle Soup", "Nihari", "Haleem", "Fried Fish Lahori", "Gajar Halwa",
        "Kashmiri Chai", "Hot Chocolate", "Fresh Orange Juice",
    ],
    "Monsoon": ["Aloo Pakora", "Chicken Pakora", "Papri Chaat", "Chickpea Chaat", "Karak Chai"],
}
IN_SEASON_MONTHS = {"Summer": {4, 5, 6, 7, 8}, "Winter": {11, 12, 1, 2}, "Monsoon": {7, 8, 9}}
SHOULDER_MONTHS = {"Summer": {3, 9}, "Winter": {3, 10}, "Monsoon": {6, 10}}

LAUNCH_DATES_2025 = {
    "Quinoa Power Bowl": "2025-03-10",
    "Peach Iced Tea": "2025-04-15",
    "Kebab Crust Pizza (Medium)": "2025-05-20",
    "Dynamite Prawns": "2025-06-12",
    "Smash Burger": "2025-10-06",
    "Pink Sauce Pasta": "2025-10-20",
    "Korean Fried Chicken Burger": "2025-11-03",
    "Lotus Biscoff Shake": "2025-11-10",
    "Nashville Hot Wrap": "2025-11-24",
    "Kunafa Cheesecake": "2025-12-01",
}
LATE_LAUNCH_CUTOFF = "2025-10-01"

DISCONTINUED = {
    "Chicken Noodle Soup": "2025-04-30",
    "Egg Fried Rice": "2025-06-30",
    "Mashed Potatoes": "2025-08-15",
    "Espresso": "2025-09-15",
}

# item -> (effective date, price change fraction); cost stays the same at these changes
PRICE_SHOCKS = {
    "Mutton Biryani": ("2025-06-01", 0.22),
    "Classic Beef Burger": ("2025-06-01", 0.25),
    "Fajita Pizza (Medium)": ("2025-07-01", 0.20),
    "Alfredo Pasta": ("2025-07-01", 0.18),
    "Oreo Shake": ("2025-06-15", 0.28),
    "Malai Boti": ("2025-07-15", 0.20),
    "Finger Fish": ("2025-06-15", 0.24),
    "Club Sandwich": ("2025-06-01", -0.15),
    "Chicken Fried Rice": ("2025-07-01", -0.15),
    "Strawberry Shake": ("2025-06-15", -0.15),
}

# key, name, type, value, start, end, min_order_value, items spec, locations spec, demand lift
PROMOTIONS = [
    ("NEWYEAR", "New Year Kickoff", "PercentOff", 15, "2025-01-01", "2025-01-10", 1500,
     {"all": True}, {"all": True}, 0.15),
    ("WINTERWARM", "Winter Warmers", "PercentOff", 20, "2025-01-11", "2025-02-15", None,
     {"categories": ["Soups", "Hot Beverages"]}, {"all": True}, 0.05),
    ("VALENTINE", "Valentine Dinner Combo", "ComboDeal", 20, "2025-02-10", "2025-02-16", 2500,
     {"categories": ["Desserts", "Pizza", "Pasta"]}, {"types": ["Urban", "Downtown", "Mall"]}, 0.12),
    ("IFTAR", "Ramadan Iftar Deal", "FixedAmountOff", 500, "2025-03-01", "2025-03-29", 3000,
     {"categories": ["BBQ & Grills", "Karahi & Handi", "Appetizers"]}, {"all": True}, 0.10),
    ("EIDFEAST", "Eid Family Feast", "ComboDeal", 25, "2025-03-31", "2025-04-06", None,
     {"items": ["BBQ Platter for 4", "Jumbo Family Pizza", "Chicken Wings Bucket", "Brownie Sundae",
                "Double Patty Burger"], "categories": ["Rice & Biryani"]}, {"all": True}, 0.15),
    ("PIZZAFEST", "Spring Pizza Fest", "BOGO", 1, "2025-04-15", "2025-04-30", None,
     {"categories": ["Pizza"]}, {"all": True}, 0.12),
    ("COOLERS", "Summer Coolers", "PercentOff", 25, "2025-05-01", "2025-06-30", None,
     {"categories": ["Cold Beverages & Shakes"]}, {"all": True}, 0.04),
    ("MALLMANIA", "Mall Mania", "PercentOff", 10, "2025-05-15", "2025-06-15", None,
     {"all": True}, {"types": ["Mall"]}, 0.15),
    ("HIGHWAY", "Highway Traveler Deal", "FixedAmountOff", 300, "2025-06-01", "2025-09-30", 1500,
     {"all": True}, {"types": ["Highway"]}, 0.10),
    ("EIDBBQ", "Eid ul Adha BBQ Nights", "PercentOff", 15, "2025-06-10", "2025-06-18", None,
     {"categories": ["BBQ & Grills"], "items": ["BBQ Platter for 4"]}, {"all": True}, 0.10),
    ("MONSOON", "Monsoon Munchies", "FixedAmountOff", 200, "2025-07-01", "2025-07-31", 1000,
     {"categories": ["Appetizers", "Hot Beverages"], "items": ["Chicken Wings Bucket"]}, {"all": True}, 0.08),
    ("AUGBOGO", "August BOGO Blast", "BOGO", 1, "2025-08-01", "2025-08-31", None,
     {"categories": ["Karahi & Handi"], "items": ["Seekh Kabab", "Chicken Tikka", "Fresh Garden Salad"]},
     {"all": True}, 0.55),
    ("AZADI", "Independence Day 14% Off", "PercentOff", 14, "2025-08-12", "2025-08-16", None,
     {"all": True}, {"all": True}, 0.20),
    ("LUNCHBACK", "Back to Work Lunch", "FixedAmountOff", 250, "2025-09-01", "2025-09-30", 1200,
     {"categories": ["Burgers & Wraps"], "items": ["Double Patty Burger"]},
     {"types": ["Downtown", "Urban"]}, 0.08),
    ("APPFEST", "App Exclusive Fest", "PercentOff", 20, "2025-09-15", "2025-10-15", 2000,
     {"all": True}, {"cities": ["Karachi", "Lahore", "Islamabad"]}, 0.10),
    ("PASTAWEEK", "Pasta Week", "PercentOff", 20, "2025-10-20", "2025-10-27", None,
     {"categories": ["Pasta"]}, {"all": True}, 0.06),
    ("PLATTERS", "Family Platter Month", "ComboDeal", 30, "2025-11-01", "2025-11-20", 3500,
     {"items": ["BBQ Platter for 4", "Jumbo Family Pizza", "Chicken Wings Bucket", "Brownie Sundae",
                "Double Patty Burger"], "categories": ["Sides & Breads", "Cold Beverages & Shakes"]},
     {"all": True}, 0.10),
    ("BLACKFRIDAY", "Black Friday Mega Sale", "PercentOff", 30, "2025-11-27", "2025-11-30", 2500,
     {"all": True}, {"all": True}, 0.40),
    ("SOUPSEASON", "Winter Soup Season", "PercentOff", 15, "2025-12-01", "2025-12-31", None,
     {"categories": ["Soups", "Hot Beverages"]}, {"all": True}, 0.04),
    ("YEAREND", "Year End Celebration", "FixedAmountOff", 750, "2025-12-20", "2025-12-31", 5000,
     {"all": True}, {"all": True}, 0.15),
]
TRAP_PROMOTION = "AUGBOGO"

HOLIDAY_MULTIPLIERS = {
    "2025-02-14": 1.45,
    "2025-03-31": 1.6, "2025-04-01": 1.5, "2025-04-02": 1.3,
    "2025-06-07": 0.7, "2025-06-08": 0.9, "2025-06-09": 1.2,
    "2025-08-14": 1.5,
    "2025-12-25": 1.3, "2025-12-31": 1.6,
}
RAMADAN = ("2025-03-01", "2025-03-30")

REVIEW_TEXT = {
    1: ["Food was cold and late.", "Very disappointing, will not order again.", "Order was wrong and tasted stale.",
        "Too oily and bland.", "Poor quality for the price."],
    2: ["Below average taste.", "Portion was too small.", "Took too long to arrive.", "Not fresh.",
        "Service was slow."],
    3: ["It was okay.", "Average, nothing special.", "Decent but overpriced.", "Taste was fine, packaging poor.",
        "Good taste but late delivery."],
    4: ["Tasty and fresh.", "Good food, will order again.", "Nice ambience and good service.",
        "Good value for money.", "Enjoyed the meal."],
    5: ["Excellent, loved it!", "Best in town.", "Perfect taste and quick service.", "Highly recommended.",
        "Amazing food and friendly staff."],
}
